### ISSUE TITLE
🐛 [Bug] ModuleNotFoundError:  No module named 'tkinter'

### ISSUE THREAD

**Issue by gitSaptarshi** [Aritra4568/wassap#2]
### Problem
Python module `tkinter` not found. Trying to run it for the first time.
### System
- OS: Fedora 33 (Workstation Edition)
- GNOME version: `3.38.3`
- Windowing System: Wayland
### Python Version
`Python 3.9.1`
### Steps to reproduce
On a fresh installation and following the `Readme.md` provided in the folder
1. Open terminal in the folder
2. Run `python client.py`
### Screenshot
![Screenshot from 2021-01-14 18-20-33](https://user-images.githubusercontent.com/37685073/104593566-e3638c80-5695-11eb-871e-356ae3b45235.png)

**Comment by Aritra4568** [comment]
this issue is solved

**Comment by gitSaptarshi** [comment]
> this issue is solved

Th problem is not solved. I can confirm it is showing the same `ModuleNotFoundError: No module named 'tkinter'`.
